// Content Writer Agent — FORBIDDEN KNOWLEDGE MODE (LOCKED)
//
// Writes platform captions for cards generated by the Trend Scout.
// The CARD itself (the visual image) is rendered by lib/card-renderer.js using the
// stored idea JSON (stamp / hook / accent_word / lead / list).
//
// This writer's only job is the surrounding CAPTION on each platform — the hook line,
// hashtags, and the single soft CTA at the end.

import { callClaude } from '../lib/claude.js';
import { recentCaptions } from '../lib/db.js';

const VOICE = `OUR VOICE (LOCKED):
- Insider warning energy. We tell you what your bank / accountant / professor / boss will not.
- Second person, blunt, calm, slightly threatening.
- Banned words: "unlock", "transform", "secret", "trick", "hack", "10x", "game-changer", "revolutionary", "you won't believe".
- Banned product nouns ANYWHERE in user-facing text (captions included): "budget", "budgeting", "cash flow", "debt payoff", "bookkeeping", "spreadsheet", "template", "tool", "app", "planner", "tracker".
  → BUT the CAPTION may use phrases like "in our bio", "link in bio", "if you want clarity on this", "for the full picture", and the destination link itself.`;

const CTA_RULES = `THE CTA (ONE soft line at the end of the caption, never in the body):
  TikTok:     "Link in bio if this hit." / "In bio if you want out of this cycle." / "Saved it for later? Link in bio."
  Instagram:  "Save this. Link in bio." / "Link in bio if you want the full picture."
  Facebook:   "If this is you: <product_url>" (URL goes at the very end)
  YouTube:    Description = 1 hook restatement + <product_url> on its own line + #Shorts + 2 niche hashtags
  Pinterest:  Description teaches first; one soft closing sentence. Destination URL set automatically.
  If product_id is null: NO product CTA. Use "Follow for more." instead.`;

const PLATFORM_RULES = `
TikTok caption: 80-140 chars. One hook restatement + 3-5 hashtags. CTA only if product-tied.
Instagram caption: 120-220 chars. Hook restatement + 4-6 hashtags blended. CTA only if product-tied.
Facebook: 2-4 short sentences. Plain. URL at the very end if product-tied.
YouTube Shorts: title = the hook itself (or 60-char curiosity edit). Description: 1 line + URL + #Shorts + 2 hashtags.
Pinterest: title 80-100 chars SEO-loaded ("3 questions your bank hopes you never ask | AF Wealth Mindset" style). Description 200-350 chars.`;

export async function writeProductVideoCopy(env, { video, product, cycle, priorCaptions }) {
  const system = `You are AF Wealth Mindset's CONTENT WRITER (forbidden-knowledge mode).

${VOICE}

${CTA_RULES}

${PLATFORM_RULES}`;

  const user = `Write platform captions for a PRODUCT VIDEO going across all platforms.

The video shows: ${video.scenario || '(spreadsheet walkthrough)'}
Character/persona in video: ${video.persona || 'generic person'}
Raw hook of the video: ${video.hook || '(none)'}

Product context (for the CTA only — never use these nouns in body):
  Name: ${product.name}
  Pitch: ${product.pitch}
  URL: ${product.url}

Cycle: ${cycle} — ${cycle > 1 ? 'Open with a DIFFERENT forbidden-knowledge angle than prior captions below.' : 'First posting.'}

Prior captions for this video (do not repeat):
${priorCaptions.length ? priorCaptions.map(c => '- [' + c.platform + '] ' + c.caption).join('\n') : '(none yet)'}

Each caption should open with a SHARP one-line hook (insider-warning energy, "what they don't tell you about ___"), then end with the soft CTA on platforms that allow it.

Return ONLY this JSON object:
{
  "variant": "<short label for this angle>",
  "tiktok":   { "caption": "...", "hashtags": ["#tag1", "#tag2"] },
  "instagram":{ "caption": "...", "hashtags": ["#tag1", "#tag2"] },
  "facebook": { "caption": "..." },
  "youtube":  { "title": "...", "description": "..." },
  "pinterest":{ "title": "...", "description": "..." }
}`;

  return callClaude(env, { system, user, response_format: 'json', max_tokens: 1500 });
}

export async function writeEngagementCopy(env, { idea, products }) {
  const focusProduct = idea.product_id ? products.find(p => p.id === idea.product_id) : null;

  // The idea body is now JSON { stamp, hook, accent_word, lead, list } from Trend Scout
  let card;
  try { card = JSON.parse(idea.body); } catch { card = { hook: idea.body, list: [] }; }

  const system = `You are AF Wealth Mindset's CONTENT WRITER (forbidden-knowledge mode).

${VOICE}

${CTA_RULES}

${PLATFORM_RULES}

This post will be rendered as a 1080×1350 BLACK + GOLD "leaked classified document" card. The card image already shows the hook, lead, and list. Your job is the surrounding CAPTION for each platform — NOT to rewrite the card.`;

  const user = `The Trend Scout produced this card (rendered as the image — do not rewrite, just hook around it):

  STAMP: ${card.stamp || '(none)'}
  HOOK: ${card.hook}
  LEAD: ${card.lead || '(none)'}
  LIST:
${(card.list || []).map((it, i) => `    ${String(i+1).padStart(2,'0')}. ${it}`).join('\n')}

${focusProduct ? `Product context (CTA only, never name the product noun):
  ${focusProduct.name} — ${focusProduct.pitch}
  URL: ${focusProduct.url}` : 'This card is NOT tied to a product — NO CTA, just "Follow for more."'}

Each caption opens with a tight forbidden-knowledge teaser of the hook (NOT a repeat — a different angle on the same provocation), invites them to read/save the image, ends with the CTA.

Return ONLY this JSON object:
{
  "variant": "<short label>",
  "focus_product_id": ${idea.product_id || 'null'},
  "tiktok":   { "caption": "...", "hashtags": ["#tag1"] },
  "instagram":{ "caption": "...", "hashtags": ["#tag1"] },
  "facebook": { "caption": "..." },
  "youtube":  { "title": "...", "description": "..." },
  "pinterest":{ "title": "...", "description": "..." }
}`;

  return callClaude(env, { system, user, response_format: 'json', max_tokens: 1500 });
}

export async function writeCopy(env, calendarEntry) {
  if (calendarEntry.type === 'product_video') {
    const priorCaptions = await recentCaptions(env, calendarEntry.video_id, 8);
    return writeProductVideoCopy(env, {
      video: {
        hook: calendarEntry.hook,
        scenario: calendarEntry.scenario,
        persona: calendarEntry.persona,
        url: calendarEntry.video_url
      },
      product: {
        name: calendarEntry.product_name,
        pitch: calendarEntry.product_pitch,
        url: calendarEntry.product_url,
        price_usd: 7.99
      },
      cycle: calendarEntry.cycle,
      priorCaptions
    });
  }
  const { results: products } = await env.DB.prepare('SELECT * FROM products').all();
  const idea = JSON.parse(calendarEntry.notes || '{}');
  return writeEngagementCopy(env, { idea, products });
}
